In [1]:
import pandas as pd
import plotly.express as px

In [3]:
spacex_df = pd.read_csv("spacex_launch_dash.csv")
spacex_df.head(5)

,Unnamed: 0,Flight Number,Launch Site,class,Payload Mass (kg),Booster Version,Booster Version Category
0,0,1,CCAFS LC-40,0,0.0,F9 v1.0 B0003,v1.0
1,1,2,CCAFS LC-40,0,0.0,F9 v1.0 B0004,v1.0
2,2,3,CCAFS LC-40,0,525.0,F9 v1.0 B0005,v1.0
3,3,4,CCAFS LC-40,0,500.0,F9 v1.0 B0006,v1.0
4,4,5,CCAFS LC-40,0,677.0,F9 v1.0 B0007,v1.0

In [10]:
# Filter data and view the filtered data
spacex_df.loc[spacex_df['Launch Site'] == 'CCAFS SLC-40']

,Unnamed: 0,Flight Number,Launch Site,class,Payload Mass (kg),Booster Version,Booster Version Category
49,49,45,CCAFS SLC-40,1,2205.00,F9 FT B1035.2,FT
50,50,47,CCAFS SLC-40,1,3696.65,F9 B4 B1043.1,B4
51,51,48,CCAFS SLC-40,0,4230.00,F9 FT B1032.2,FT
52,52,50,CCAFS SLC-40,0,6092.00,F9 B4 B1044,B4
53,53,52,CCAFS SLC-40,0,2647.00,F9 B4 B1039.2,B4
54,54,53,CCAFS SLC-40,1,362.00,F9 B4 B1045.1,B4
55,55,56,CCAFS SLC-40,0,5384.00,F9 B4 B1040.2,B4